export const gamesToSeed = [
  {
    _id: "642eaeb63d774e3fb3a7bea1",
    systemGameName: "csgo",
    commonGameName: "Counter-Strike 2",
    gameDescription:
      "Mногопользовательская компьютерная игра, разработанная компаниями Valve и Hidden Path Entertainment. Выпуск игры для персональных компьютеров на операционных системах Windows и macOS, также игровых приставках Xbox 360 и PlayStation 3 состоялся 21 августа 2012 года",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/COUNTER-STRIKE%202.png",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "21.08.2012",
    publisher: "Valve Beijing Perfect World",
    gameVideoUrl: "https://www.youtube.com/watch?v=nSE38xjMLqE",
    gameImages: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_d196d945c6170e9cadaf67a6dea675bd5fa7a046.1920x1080.jpg?t=1668125812",
      "https://isport.ua/i/71/36/06/4/7136064/image_main/8792a943817b88ae6ec142b1fd8c336b-resize_crop_1Xquality_100Xallow_enlarge_0Xw_1200Xh_630.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/730/ss_118cb022b9a43f70d2e5a2df7427f29088b6b191.1920x1080.jpg?t=1668125812",
      "https://pbs.twimg.com/amplify_video_thumb/1624164001448964096/img/HV9cTfnV-pa4GfSi.jpg",
    ],
    exactingness: "39",
    createdAt: "2023-04-06T11:36:22.133Z",
    updatedAt: "2024-07-03T10:35:27.506Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Counter_Strike_2/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Counter_Strike_2/logo.png",
    gameVideoLauncherUrl: "nSE38xjMLqE?si=joAvli9SGu1Ke3LE",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Counter_Strike_2/hero_1440x800.jpg",
  },
  {
    _id: "65154bae59c15dd8d5497a64",
    systemGameName: "rust",
    commonGameName: "Rust",
    gameDescription:
      "Rust — комп'ютерна гра в жанрі симулятора виживання була створена незалежною британською студією Facepunch[2], очолюваною з 2014 року Гаррі Ньюменом. Гра вийшла на платформах Windows та MacOS. З грудня 2013 гра була в ранньому доступі. Випуск гри відбувся 8 лютого 2018 року.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/RUST.jpeg",
    gameClass: "VIP",
    genre: "SURVIVAL",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=LGcECozNXEw",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T09:47:26.007Z",
    updatedAt: "2024-07-03T10:36:00.609Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Rust/boxart_600x900.jpg",
    gameLogo: "https://miraplay.cloud/images/Game_Library_assest/Rust/logo.png",
    gameVideoLauncherUrl: "LGcECozNXEw?si=7avo1IxgnO3voATf",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Rust/hero_1440x800.jpg",
  },
  {
    _id: "65154bf859c15dd8d5497a6c",
    systemGameName: "cyberpunk_2077",
    commonGameName: "Cyberpunk 2077",
    gameDescription:
      "Cyberpunk 2077 – комп'ютерна гра від авторів серії The Witcher, створена за мотивами настільної рольової гри Cyberpunk 2020 Майка Пондсміта. Гравця відправляють у 2077 рік, де створений ним персонаж має вижити у футуристичному місті Найт-Сіті, Каліфорнія.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/CYBERPUNK%202077.jpeg",
    gameClass: "VIP",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=aSrFWinrkeQ",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T09:48:40.048Z",
    updatedAt: "2024-07-03T10:37:15.146Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Cyberpunk_2077/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Cyberpunk_2077/logo.png",
    gameVideoLauncherUrl: "Ugb80d5lxEM?si=XuCKMvTjFZrlIucW",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Cyberpunk_2077/hero_1440x800.jpg",
  },
  {
    _id: "65154c3c59c15dd8d5497a77",
    systemGameName: "gta5",
    commonGameName: "Grand Theft Auto V",
    gameDescription:
      "Grand Theft Auto V - це не лише до абсурду приємна відеогра, а й розумна та дотепна сатира на сучасну Америку. Вона є удосконаленням всього того, що принесла GTA IV. Вона технічно досконаліша у всіх мислимих відносинах, але при цьому по-своєму амбітна. Жоден інший світ у відеоіграх не наближається до цього за розміром чи масштабом, а за почуттям гумору та даром до хаосу ховається гострий розум. Вона розповідає переконливу, непередбачувану та провокаційну історію, ніколи не дозволяючи їй стати на шляху ваших самостійних пригод по Сан-Андреасу. Це одна з найкращих відеоігор, коли-небудь створених.",
    gameLaunchers: ["Steam", "Epic Games"],
    gameImage: "https://miraplay.cloud/images/GRAND%20THEFT%20AUTO%20V.jpg",
    gameClass: "VIP",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=hvoD7ehZPcM",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T09:49:48.326Z",
    updatedAt: "2024-07-03T10:37:43.052Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Grand_Theft_Auto_V/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Grand_Theft_Auto_V/logo.png",
    gameVideoLauncherUrl: "hvoD7ehZPcM?si=UB3ad_suoVtRcMzJ",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Grand_Theft_Auto_V/hero_1440x800.jpg",
  },
  {
    _id: "65154cf659c15dd8d5497a91",
    systemGameName: "wowarships",
    commonGameName: "World of Warships",
    gameDescription:
      "World of Warships (з англ. «Світ військових кораблів»; з 16 серпня 2011 року по 2 серпня 2012 року World of Battleships) — комп'ютерна, клієнтська масова розрахована на багато користувачів онлайн-гра в реальному часі в жанрі аркадного симулятора морських битв на кораблях в тому числі Arpeggio of Blue Steel, High School Fleet та інших, анонсована 16 серпня 2011 видавцем і розробником онлайн-ігор кіпрською компанією Wargaming.net, і вийшла в реліз 17 вересня 2015 року.\nСпочатку гра вийшла для Microsoft Windows, з 2016 доступний запуск на MacOS через Mac Wrapper від компанії CodeWeavers.",
    gameLaunchers: ["Wargaming"],
    gameImage: "https://miraplay.cloud/images/WORLD%20OF%20WARSHIPS.jpg",
    gameClass: "STANDART",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=TemOkfZe5_4",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T09:52:54.820Z",
    updatedAt: "2024-07-03T10:38:04.594Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Warships/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Warships/logo.png",
    gameVideoLauncherUrl: "fDqwAiVR5JU?si=eJuYvrrPBrXn-5CS",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Warships/hero_1440x800.jpg",
  },
  {
    _id: "65154db359c15dd8d5497aa9",
    systemGameName: "wargaming",
    commonGameName: "Wargaming",
    gameDescription:
      "Wargaming.net Game Center — платформа дистрибуції (додаток для запуску ігор), в якому зібрані всі ваші ігри Wargaming, а також в ньому можна читати новини про майбутні функції та особливості, дивитися відео та знаходити приголомшливі знижки!",
    gameLaunchers: ["Wargaming"],
    gameImage: "https://miraplay.cloud/images/WARGAMING.jpeg",
    gameClass: "STANDART",
    genre: "LAUNCHERS",
    inTop: true,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=MYtxWvT2Fh0",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T09:56:03.504Z",
    updatedAt: "2024-07-03T10:38:27.729Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Wargaming/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Wargaming/logo.png",
    gameVideoLauncherUrl: "MYtxWvT2Fh0?si=Hh8wu0ALtmUmuNyL",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Wargaming/hero_1440x800.jpg",
  },
  {
    _id: "65154e2a59c15dd8d5497ab5",
    systemGameName: "days_gone",
    commonGameName: "Days gone",
    gameDescription:
      "Days Gone — екшен від третьої особи, дія якої відбувається у відкритому постапокаліптичному світі. Гравці візьмуть на себе роль Дікон Сейнт-Джон, байкера, який у новому світі веде мандрівний спосіб життя. Йому належить боротися за життя, борючись як з фрикерами, так і з тими, хто вижив.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/DAYS%20GONE.jpeg",
    gameClass: "VIP",
    genre: "SURVIVAL",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=DzSgio7Fy3c",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T09:58:02.055Z",
    updatedAt: "2024-07-03T10:38:57.779Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Days_Gone/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Days_Gone/logo.png",
    gameVideoLauncherUrl: "FKtaOY9lMvM?si=gmJco389r_XsTAcL",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Days_Gone/hero_1440x800.jpg",
  },
  {
    _id: "65154e7959c15dd8d5497ac1",
    systemGameName: "albion_online",
    commonGameName: "Albion Online",
    gameDescription:
      "Albion Online — кросплатформова масова розрахована на багато користувачів рольова онлайн-гра в середньовічній стилістиці, розроблена і випущена Sandbox Interactive.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/ALBION%20ONLINE.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=xhLxGK0MvnA",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T09:59:21.413Z",
    updatedAt: "2024-07-03T10:39:21.056Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Albion_Online/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Albion_Online/logo.png",
    gameVideoLauncherUrl: "xhLxGK0MvnA?si=eJJCIb5iqOX_pceq",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Albion_Online/hero_1440x800.jpg",
  },
  {
    _id: "651554ef59c15dd8d5497bba",
    systemGameName: "7_days_to_die",
    commonGameName: "7 days to die",
    gameDescription:
      "7 Days to Die - це гра з відкритим ігровим світом, дії якої відбуваються в жорстокому і невблаганному пост-апокаліптичному світі, наповненому зомбі, яка включає незвичайне поєднання шутера від першої особи, жахів виживання, захисту фортець і рольових ігор.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/7%20DAYS%20TO%20DIE.jpg",
    gameClass: "VIP",
    genre: "SURVIVAL",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=lmPHz0dwBj4",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:26:55.712Z",
    updatedAt: "2024-07-03T11:04:56.193Z",
    __v: 0,
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/7_Days_to_Die/logo.png",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/7_Days_to_Die/boxart_600x900.jpg",
    gameVideoLauncherUrl: "lmPHz0dwBj4?si=H7XwVOz5dzS9-Rsb",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/7_Days_to_Die/hero_1440x800.jpg",
  },
  {
    _id: "6515552f59c15dd8d5497bc3",
    systemGameName: "pubg",
    commonGameName: "PUBG",
    gameDescription:
      "PlayerUnknown’s Battlegrounds(скор. PUBG, також відома як PUBG: Battlegrounds) — розрахована на багато користувачів онлайн-гра в жанрі королівської битви, що розробляється і видається студією PUBG Corporation, дочірньою компанією корейського видавця Bluehole. Офіційною дистрибуцією гри біля Росії займається Mail.Ru Group[3][4]. Гра заснована на попередніх модифікаціях для інших ігор, створених Бренданом Гріном (англ. Brendan Greene) під псевдонімом PlayerUnknown, концепція яких була натхненна японським фільмом Королівська битва 2000 року. У результаті це призвело до створення самостійної гри, де Грін виступив як провідний геймдизайнер. У грі до 100 гравців, які десантуються на острів, після чого шукають спорядження та зброю, щоб убити інших учасників і при цьому залишитися в живих. Доступна безпечна зона на внутрішньоігровій карті з часом починає зменшуватися, роблячи доступний простір тіснішим, щоб зіштовхувати між собою гравців. Останній гравець, що вижив, або команда перемагає в раунді.\n\nPlayerUnknown's Battlegrounds була випущена в Steam за програмою раннього доступу 23 березня 2017 для операційної системи Windows[5]. Протягом перших семи місяців після виходу було продано більше 13 млн копій гри, а пікова кількість гравців досягла більше 2 мільйонів осіб до кінця року, що зробило її однією з найпопулярніших ігор Steam [6]. 31 жовтня продаж PUBG перевищив 18 млн копій. Повну версію гри було випущено 21 грудня 2017 року. Вихід для Xbox One під видавництвом Microsoft Studios відбувся 12 грудня за програмою раннього доступу[7], але вже 4 вересня 2018 року відбувся офіційний реліз. 19 березня 2018 року була випущена мобільна версія PUBG Mobile для Android та iOS за моделлю free-to-play. Версія для PlayStation 4 була анонсована в листопаді 2018 року і випущена 7 грудня 2018 року.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/PUBG.jpg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=OUeQjwzSbc4",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:27:59.724Z",
    updatedAt: "2024-07-03T10:39:39.890Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/PUBG_BATTLEGROUNDS/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/PUBG_BATTLEGROUNDS/logo.png",
    gameVideoLauncherUrl: "u1oqfdh4xBY?si=olARNZYJllnyaHL-",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/PUBG_BATTLEGROUNDS/hero_1440x800.jpg",
  },
  {
    _id: "651555f859c15dd8d5497bd7",
    systemGameName: "dayz",
    commonGameName: "DayZ",
    gameDescription:
      "DayZ — розрахована на багато користувачів комп'ютерна гра в жанрі survival horror з відкритим світом, що розробляється компанією Bohemia Interactive. Гра є ремейком однойменної модифікації до Arma 2, створеної геймдизайнером Діном Холлом. Рання альфа-версія гри для Windows була випущена наприкінці 2013 року у мережі цифрової дистрибуції Steam. Реліз гри на платформі Windows відбувся 13 грудня 2018[1][2]. Версія для PlayStation 4 вийшла 29 травня 2019 року.\n\nДія гри відбувається у вигаданій пострадянській державі Чорнорусія, жителі якої в результаті якогось катаклізму перетворилися на агресивні зомбі. Керований гравцем персонаж повинен вижити у ворожому оточенні, уникаючи ворогів і видобуваючи в покинутих будинках зброю, їжу та інші припаси. Одночасно з ним на тій же карті діють інші гравці; кожен гравець має право вбивати персонажів інших гравців, уникати їх або поєднуватися з ними в групи для спільного виживання.\n\nРозробка гри розпочалася у 2012 році, коли автор модифікації Дін Холл приєднався до компанії Bohemia Interactive. Незважаючи на статус ранньої альфа-версії та відсутність у грі багатьох запланованих можливостей, на травень 2014 року було продано понад 2 мільйони копій гри, що принесло розробникам близько 100 мільйонів доларів США[3].",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/DAYZ.jpg",
    gameClass: "VIP",
    genre: "SURVIVAL",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=7jk8prJA9nI",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:31:20.439Z",
    updatedAt: "2024-07-03T10:40:14.587Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/DayZ/boxart_600x900.jpg",
    gameLogo: "https://miraplay.cloud/images/Game_Library_assest/DayZ/logo.png",
    gameVideoLauncherUrl: "fJmMbl3bqE0?si=Q2RG0xJYGVG2qllj",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/DayZ/hero_1440x800.jpg",
  },
  {
    _id: "6515564c59c15dd8d5497be1",
    systemGameName: "dota2",
    commonGameName: "DOTA 2",
    gameDescription:
      "Dota 2 — комп'ютерна розрахована на багато користувачів командна гра в жанрі multiplayer online battle arena, розроблена корпорацією Valve. Гра є продовженням DotA — картки-модифікації для гри Warcraft III: Reign of Chaos і доповнення до неї Warcraft III: The Frozen Throne. Гра зображує бій на карті особливого виду; у кожному матчі беруть участь дві команди по п'ять гравців, які управляють «героями» — персонажами з різними наборами здібностей. Для перемоги в матчі команда має знищити особливий об'єкт-«фортеця», що належить ворожій стороні, та захистити від знищення власну «фортецю». Dota 2 працює за моделлю free-to-play з елементами мікроплатежів.\n\nРозробка гри розпочалася у 2009 році, коли компанія Valve прийняла на роботу основного розробника DotA – IceFrog, а влітку 2010 року подала заявку на реєстрацію цієї торгової марки. 13 жовтня 2010 року на ігровому порталі Game Informer гра була анонсована до виходу в 2011 [6]. 15 серпня 2011 року в офіційному блозі було опубліковано трейлер до гри. Dota 2 вийшла у липні 2013 року після того, як два роки перебувала у стадії бета-тестування.\n\nСпочатку Dota 2 була випущена на ігровому движку Source, після чого в 2015 році була портована на Source 2, ставши першою грою, що працює на ньому. У Dota 2 передбачена можливість створювати режими гри, оформлення карти і косметичні предмети для героїв, після чого додати їх в Dota 2 за допомогою Steam Workshop. Dota 2 є однією з найбільш популярних ігор у Steam і отримала загалом позитивні відгуки критиків за ігровий процес, якість виробництва та збереження позитивних сторін своєї попередниці. Серед основних недоліків гри було відзначено складність навчання.\n\nDota 2 є активною кіберспортивною дисципліною, в якій професійні команди з усього світу змагаються у різних лігах та турнірах. Преміум-турніри з Dota 2 мають призові фонди в мільйони доларів, які не раз ставали найбільшими в історії кіберспорту. Найбільший турнір з гри - The International, що щорічно проводиться Valve. Починаючи з сезону 2017/18 Valve також організовує Dota Pro Circuit – професійний сезон, що проводиться протягом року. Великі професійні турніри з Dota 2 транслюються на відеострімінгових сервісах, іноді набираючи понад мільйон глядачів одночасно. Людей, які грають у Dota 2, часто називають «дотерами».",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/DOTA%202.jpg",
    gameClass: "STANDART",
    genre: "MOBA",
    inTop: false,
    releaseDate: "",
    publisher: "Valve",
    gameVideoUrl: "https://www.youtube.com/watch?v=SmnqsdeHFT0",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:32:44.628Z",
    updatedAt: "2024-07-03T10:40:29.152Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Dota_2/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Dota_2/logo.png",
    gameVideoLauncherUrl: "SmnqsdeHFT0?si=djN54A1ZP2TZm8ph",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Dota_2/hero_1440x800.jpg",
  },
  {
    _id: "651556b559c15dd8d5497bed",
    systemGameName: "fortnite",
    commonGameName: "Fortnite",
    gameDescription:
      "Fortnite — королівська битва і кооперативна пісочниця на виживання, основними механіками якої є дослідження, збирання ресурсів, будівництво укріплених будівель і боротьба з хвилями зомбі.",
    gameLaunchers: ["Epic Games"],
    gameImage: "https://miraplay.cloud/images/FORTNITE.jpeg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "Epic games",
    gameVideoUrl: "https://www.youtube.com/watch?v=WJW-bzXZM8M",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:34:29.561Z",
    updatedAt: "2024-07-03T10:40:51.965Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Fortnite/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Fortnite/logo.png",
    gameVideoLauncherUrl: "WJW-bzXZM8M?si=DVZrviZQTfP1hBdV",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Fortnite/hero_1440x800.jpg",
  },
  {
    _id: "6515570a59c15dd8d5497bf7",
    systemGameName: "forza_horizon5",
    commonGameName: "Forza Horizon 5",
    gameDescription:
      "Forza Horizon 5 — комп'ютерна гра у жанрі аркадного гоночного симулятора. Як розробник виступає компанія Playground Games, а як видавець — Xbox Game Studios. Гра була анонсована у червні 2021 року на заході E3 2021. Вихід гри відбувся 9 листопада 2021 року.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/FORZA%20HORIZON%205.jpg",
    gameClass: "VIP",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "Xbox Game Studios",
    gameVideoUrl: "https://www.youtube.com/watch?v=FYH9n37B7Yw",
    gameImages: [
      "https://tpucdn.com/review/gainward-geforce-rtx-4080-phoenix-gs/images/forza-horizon-5.jpg",
    ],
    exactingness: "",
    createdAt: "2023-09-28T10:35:54.909Z",
    updatedAt: "2024-07-03T10:41:51.281Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Forza_Horizon_5/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Forza_Horizon_5/logo.png",
    gameVideoLauncherUrl: "FYH9n37B7Yw?si=fWYElZ_xUWjYYuHm",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Forza_Horizon_5/hero_1440x800.jpg",
  },
  {
    _id: "651557f159c15dd8d5497c10",
    systemGameName: "eve_online",
    commonGameName: "EVE Online",
    gameDescription:
      "EVE Online (вимовляється як Ів Онлайн) — масова розрахована на багато користувачів онлайн-гра з науково-фантастичним сюжетом, дія якої розгортається в космосі. Гра розроблена ісландською компанією CCP Games. З травня по грудень 2003 видавалася Simon & Schuster Interactive [2] (згодом CCP Games викупила права на поширення). У вересні 2018 року було оголошено про придбання її корейською компанією Pearl Abyss[3].",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/EVE%20ONLINE.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "CCP Games",
    gameVideoUrl: "https://www.youtube.com/watch?v=zQciMy_Pr0Q",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:39:45.520Z",
    updatedAt: "2024-07-03T10:42:01.608Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/EVE_Online/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/EVE_Online/logo.png",
    gameVideoLauncherUrl: "zQciMy_Pr0Q?si=EFU1kU1T1_Mk26sa",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/EVE_Online/hero_1440x800.jpg",
  },
  {
    _id: "6515588b59c15dd8d5497c25",
    systemGameName: "path_of_exile",
    commonGameName: "Path of Exile",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/PATH%20OF%20EXILE.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "Grinding Gear Games",
    gameVideoUrl: "https://www.youtube.com/watch?v=en8no_jEfAQ",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:42:19.274Z",
    updatedAt: "2024-07-03T10:42:19.326Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Path_of_Exile/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Path_of_Exile/logo.png",
    gameVideoLauncherUrl: "PP7yRXdHAT0?si=K5aA2F785Xcqbrz1",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Path_of_Exile/hero_1440x800.jpg",
  },
  {
    _id: "651558d859c15dd8d5497c31",
    systemGameName: "battlenet",
    commonGameName: "Battle.net",
    gameDescription:
      "Беріть участь у карткових дуелях з легендами всесвіту Warcraft, б'йтесь на міжгалактичному полі бою або командуйте арміями серед зірок. З додатком Battle.net ви можете завантажувати Hearthstone, StarCraft, Heroes of the Storm та інші ігри Blizzard грати у них безкоштовно протягом необмеженого часу.",
    gameLaunchers: ["battle.net"],
    gameImage: "https://miraplay.cloud/images/BATTLE.NET.jpg",
    gameClass: "STANDART",
    genre: "LAUNCHERS",
    inTop: true,
    releaseDate: "",
    publisher: "",
    gameVideoUrl:
      "https://www.youtube.com/watch?v=z3dUax2MUhg&pp=ygUSQmF0dGxlLm5ldCB0cmFpbGVy",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:43:36.852Z",
    updatedAt: "2024-07-03T10:42:42.446Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Battle.net/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Battle.net/logo.png",
    gameVideoLauncherUrl: "4JPpQJv7TyA?si=3i7ZzxIb8dH-uODP",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Battle.net/hero_1440x800.jpg",
  },
  {
    _id: "6515594a59c15dd8d5497c3c",
    systemGameName: "war_thunder",
    commonGameName: "War Thunder",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/WAR%20THUNDER.jpg",
    gameClass: "STANDART",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=pzgPXOw2plI",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:45:30.333Z",
    updatedAt: "2024-07-03T10:42:55.999Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/War_Thunder/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/War_Thunder/logo.png",
    gameVideoLauncherUrl: "pzgPXOw2plI?si=X2W7YgetI4u0-PWL",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/War_Thunder/hero_1440x800.jpg",
  },
  {
    _id: "65155c5b59c15dd8d5497c69",
    systemGameName: "steam",
    commonGameName: "Steam",
    gameDescription:
      'Steam - це онлайн-платформа від розробника ігор Valve, де ви можете купувати, грати, створювати та обговорювати ігри для ПК. На платформі розміщені тисячі ігор (а також завантажуваний контент, або DLC, і функції користувача, звані "модами") від великих розробників та інди-дизайнерів.',
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/STEAM.jpeg",
    gameClass: "STANDART",
    genre: "LAUNCHERS",
    inTop: true,
    releaseDate: "",
    publisher: "Valve",
    gameVideoUrl: "https://www.youtube.com/watch?v=e8jv24NjOWQ&t=9s",
    gameImages: [
      "https://clan.akamai.steamstatic.com/images/41316928/f7f5587c77587cc8ae5eb50e39defcbcc3acaa88.jpg",
    ],
    exactingness: "",
    createdAt: "2023-09-28T10:58:35.432Z",
    updatedAt: "2024-07-03T10:43:14.644Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Steam/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Steam/logo.png",
    gameVideoLauncherUrl: "e8jv24NjOWQ?si=ViCRBvx--zrT-yIP",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Steam/hero_1440x800.jpg",
  },
  {
    _id: "65155cac59c15dd8d5497c70",
    systemGameName: "genshin_impact",
    commonGameName: "Genshin impact",
    gameDescription:
      "Genshin Impact — це барвиста анімешна Action RPG з відкритим світом від китайської компанії HoYoverse. Гра вийшла на платформі PC, а також мобільних пристроях під керуванням операційних систем Android та iOS. Дія в ній розгортається у світі Тейвата, де всі сповідують релігію «Сімеро». Увійшовши в гру, користувачі можуть насолодитися: опрацьованим лором, мангою, що підкріплюється, і анімаційними роликами, приємною оку графікою, глибокими персонажами, декількома класичними класами і hack'n'slash бойовою системою.",
    gameLaunchers: ["Epic Games"],
    gameImage: "https://miraplay.cloud/images/GENSHIN%20IMPACT.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "HoYoverse",
    gameVideoUrl: "https://www.youtube.com/watch?v=lMdsrZ1otlA",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T10:59:56.352Z",
    updatedAt: "2024-07-03T10:43:28.278Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Genshin_Impact/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Genshin_Impact/logo.png",
    gameVideoLauncherUrl: "lMdsrZ1otlA?si=lw5DcAXbYE_7HeOI",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Genshin_Impact/hero_1440x800.jpg",
  },
  {
    _id: "65155d38b676067d292e4238",
    systemGameName: "wotanks",
    commonGameName: "World Of Tanks",
    gameDescription:
      "World of Tanks (з англ. — «Світ танків»; скор. WoT) це командна масова розрахована на багато користувачів онлайн-гра, присвячена броньованим машинам середини XX століття. У розпорядженні гравців понад 40 бойових карток, створених на основі реальних локацій часів Другої світової війни, та історично достовірна техніка 11 націй загальною чисельністю понад 600 одиниць.\n\n",
    gameLaunchers: ["Wargaming"],
    gameImage: "https://miraplay.cloud/images/WORLD%20OF%20TANKS.jpg",
    gameClass: "STANDART",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "Wargaming.net",
    gameVideoUrl: "https://www.youtube.com/watch?v=0p87LvpKZqs",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:02:16.927Z",
    updatedAt: "2024-07-03T10:43:52.359Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Tanks/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Tanks/logo.png",
    gameVideoLauncherUrl: "mV3YOW185Lg?si=oK8cHf8yC-VcTRVT",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Tanks/hero_1440x800.jpg",
  },
  {
    _id: "65155e04b676067d292e4275",
    systemGameName: "epicgames",
    commonGameName: "Epic Games",
    gameDescription:
      'Epic Games Launcher - це оболонка для запуску ігор, розроблених або виданих компанією Epic Games. Подібні додатки створюються багатьма не найбільшими видавцями і створені швидше для іміджу, ніж для особливо важливого функціонального призначення. Серед проектів, які запускатимуться за допомогою цієї програми, значаться: Paragon, Fortnite, Unreal Tournament, ARK та Shadow Complex. Завантажити будь-яку з них можна безпосередньо із "лаунчера". Також програма служить для завантаження оновлень та керування статусом облікового запису. Обліковий запис, до речі, теж можна створити безпосередньо при першому запуску програми.\n',
    gameLaunchers: ["Epic Games"],
    gameImage: "https://miraplay.cloud/images/EPIC%20GAMES.png",
    gameClass: "STANDART",
    genre: "LAUNCHERS",
    inTop: true,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=nv8lkz1a42M",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:05:40.153Z",
    updatedAt: "2024-07-03T10:44:02.970Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Epic_Games/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Epic_Games/logo.png",
    gameVideoLauncherUrl: "nv8lkz1a42M?si=I5GqMD-64ObxV0No",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Epic_Games/hero_1440x800.jpg",
  },
  {
    _id: "65155e66b676067d292e4283",
    systemGameName: "team_fortress_2",
    commonGameName: "Team fortess 2",
    gameDescription:
      'Team Fortress 2 - це гротескний "шпигунський" бойовик, виконаний у стилі 50-х років минулого століття. Гравці, розділені на дві команди - Червону та Синю, воюють один з одним, виступаючи за кілька різних бойових класів, кожен з яких озброєний унікальною зброєю.',
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/TEAM%20FORTESS%202.png",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "Valve",
    gameVideoUrl: "https://www.youtube.com/watch?v=N7ZafWA2jd8",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:07:18.159Z",
    updatedAt: "2024-07-03T10:44:17.229Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Team_Fortress_2/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Team_Fortress_2/logo.png",
    gameVideoLauncherUrl: "N7ZafWA2jd8?si=zbFHePDRbV3q2R0p",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Team_Fortress_2/hero_1440x800.jpg",
  },
  {
    _id: "651561b1b676067d292e42c7",
    systemGameName: "NARAKA BLADEPOINT",
    commonGameName: "NARAKA: BLADEPOINT",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/NARAKA%20BLADEPOINT.jpeg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=kp4WrQp6pUg",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:21:21.927Z",
    updatedAt: "2024-07-03T10:44:26.833Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Naraka_Bladepoint/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Naraka_Bladepoint/logo.png",
    gameVideoLauncherUrl: "kp4WrQp6pUg?si=ptpTmKRx8sPjBqB2",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Naraka_Bladepoint/hero_1440x800.jpg",
  },
  {
    _id: "651562ffb676067d292e42eb",
    systemGameName: "Call of Duty",
    commonGameName: "Call of Duty: Warzone 2.0",
    gameDescription:
      'Call of Duty: Warzone — мультиплатформна free-to-play комп\'ютерна гра в жанрі розрахованого на багато шутера від першої особи і королівської битви.\n\nWarzone підтримує два базові режими гри - "королівська битва" і "видобуток". Warzone стала третьою грою, після режимів «Blackout» у Call of Duty: Black Ops 4 (2018) та «Королівська битва» у Call of Duty: Mobile, із серії Call of Duty, де підтримується режим королівської битви. Warzone відрізняється від Black Ops 4 заохоченням накопичення ігрової валюти замість пошуку обладнання для зброї, розкиданої по карті. Warzone використовує бої, в яких бере участь до 150 гравців, на відміну від інших подібних ігор, які підтримують лише до ста людей в одному бою.',
    gameLaunchers: ["battle.net"],
    gameImage:
      "https://miraplay.cloud/images/CALL%20OF%20DUTY%20WARZONE%202.0.jpg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "Activision",
    gameVideoUrl: "https://www.youtube.com/watch?v=dm7cJsTXm0g",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:26:55.436Z",
    updatedAt: "2024-07-03T10:44:43.715Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Call_of_Duty_Warzone_2.0/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Call_of_Duty_Warzone_2.0/logo.png",
    gameVideoLauncherUrl: "dm7cJsTXm0g?si=j8R_ebDp37OStoVG",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Call_of_Duty_Warzone_2.0/hero_1440x800.jpg",
  },
  {
    _id: "6515657eb676067d292e434b",
    systemGameName: "Eternal Return",
    commonGameName: "Eternal Return",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/ETERNAL%20RETURN.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=KqDLrvrl_p0",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:37:34.979Z",
    updatedAt: "2024-07-03T10:44:57.893Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Eternal_Return/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Eternal_Return/logo.png",
    gameVideoLauncherUrl: "KqDLrvrl_p0?si=3raojqyd_OeCkK7T",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Eternal_Return/hero_1440x800.jpg",
  },
  {
    _id: "65156650b676067d292e4386",
    systemGameName: "Summoners War: Chronicles",
    commonGameName: "Summoners War: Chronicles",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage:
      "https://miraplay.cloud/images/SUMMONERS%20WAR%20CHRONICLES.jpeg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=DkLo0JGs4RM",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:41:04.412Z",
    updatedAt: "2024-07-03T10:45:08.341Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Summoners_War_Chronicles/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Summoners_War_Chronicles/logo.png",
    gameVideoLauncherUrl: "DkLo0JGs4RM?si=waPuOONng1BG9Vlu",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Summoners_War_Chronicles/hero_1440x800.jpg",
  },
  {
    _id: "651567bab676067d292e43d4",
    systemGameName: "the_sims™_4",
    commonGameName: "The Sims™ 4",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/THE%20SIMS%E2%84%A2%204.jpeg",
    gameClass: "VIP",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=DyNv44QR14g",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:47:06.682Z",
    updatedAt: "2024-07-03T10:45:25.932Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/The_Sims_4/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/The_Sims_4/logo.png",
    gameVideoLauncherUrl: "sdhU5tRCqYc?si=K1cEZcEzcIMSxa7v",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/The_Sims_4/hero_1440x800.jpg",
  },
  {
    _id: "65156872b676067d292e4410",
    systemGameName: "Destiny 2",
    commonGameName: "Destiny 2",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/DESTINY%202.jpg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=hdWkpbPTpmE",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:50:10.503Z",
    updatedAt: "2024-07-03T10:45:36.079Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Destiny_2/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Destiny_2/logo.png",
    gameVideoLauncherUrl: "hdWkpbPTpmE?si=r65hOwbYzsxL0kFj",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Destiny_2/hero_1440x800.jpg",
  },
  {
    _id: "651568eeb676067d292e4422",
    systemGameName: "SMITE",
    commonGameName: "SMITE®",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/SMITE%C2%AE.jpg",
    gameClass: "STANDART",
    genre: "MOBA",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=9IZTss4ud1k",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:52:14.567Z",
    updatedAt: "2024-07-03T10:45:46.813Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/SMITE/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/SMITE/logo.png",
    gameVideoLauncherUrl: "9IZTss4ud1k?si=TnBAZ8FJ0CGXyPZQ",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/SMITE/hero_1440x800.jpg",
  },
  {
    _id: "651569ccb676067d292e4433",
    systemGameName: "SYNCED",
    commonGameName: "SYNCED",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/SYNCED.jpg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=MVZsAsqgS0g",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:55:56.134Z",
    updatedAt: "2024-07-03T10:46:02.929Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/SYNCED/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/SYNCED/logo.png",
    gameVideoLauncherUrl: "MVZsAsqgS0g?si=VBcN5lBRpyNdLwAJ",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/SYNCED/hero_1440x800.jpg",
  },
  {
    _id: "65156a36b676067d292e443d",
    systemGameName: "Magic: The Gathering Arena",
    commonGameName: "Magic: The Gathering Arena",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage:
      "https://miraplay.cloud/images/MAGIC%20THE%20GATHERING%20ARENA.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=1nNuG0wx0fU",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T11:57:42.350Z",
    updatedAt: "2024-07-03T10:46:16.867Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Magic_The_Gathering_Arena/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Magic_The_Gathering_Arena/logo.png",
    gameVideoLauncherUrl: "1nNuG0wx0fU?si=_mDm2HyikpKkfEPM",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Magic_The_Gathering_Arena/hero_1440x800.jpg",
  },
  {
    _id: "65157030b676067d292e448a",
    systemGameName: "War Robots",
    commonGameName: "War Robots",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/WAR%20ROBOTS.png",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=fZw4YYXsT5Y",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T12:23:12.523Z",
    updatedAt: "2024-07-03T10:46:36.020Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/War_Robots/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/War_Robots/logo.png",
    gameVideoLauncherUrl: "fZw4YYXsT5Y?si=tbtwq30KiaktZI5o",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/War_Robots/hero_1440x800.jpg",
  },
  {
    _id: "651570a9b676067d292e4495",
    systemGameName: "Overwatch® 2",
    commonGameName: "Overwatch® 2",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/OVERWATCH%C2%AE%202.jpg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=z7usG2oKONE",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T12:25:13.840Z",
    updatedAt: "2024-07-03T10:47:28.445Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Overwatch_2/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Overwatch_2/logo.png",
    gameVideoLauncherUrl: "z7usG2oKONE?si=ghpQGBcE9IntAQsy",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Overwatch_2/hero_1440x800.jpg",
  },
  {
    _id: "651572a9b676067d292e44bd",
    systemGameName: "Brawlhalla",
    commonGameName: "Brawlhalla",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/BRAWLHALLA.jpg",
    gameClass: "STANDART",
    genre: "FIGHTING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=Odj7pIsHRt0",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T12:33:45.518Z",
    updatedAt: "2024-07-03T10:47:40.748Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Brawlhalla/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Brawlhalla/logo.png",
    gameVideoLauncherUrl: "Odj7pIsHRt0?si=4KzOmrY0fiZSWBIq",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Brawlhalla/hero_1440x800.jpg",
  },
  {
    _id: "6515739cb676067d292e44eb",
    systemGameName: "Warhaven",
    commonGameName: "Warhaven",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/WARHAVEN.jpg",
    gameClass: "STANDART",
    genre: "FIGHTING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=C8HYbo73XI4",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T12:37:48.234Z",
    updatedAt: "2024-07-03T10:47:52.834Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Warhaven/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Warhaven/logo.png",
    gameVideoLauncherUrl: "C8HYbo73XI4?si=n6FHamsOI7cXHLr7",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Warhaven/hero_1440x800.jpg",
  },
  {
    _id: "651573dcb676067d292e44f4",
    systemGameName: "UNDECEMBER",
    commonGameName: "UNDECEMBER",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/UNDECEMBER.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=avzxX43SVME",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T12:38:52.186Z",
    updatedAt: "2024-07-03T10:48:10.709Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Undecember/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Undecember/logo.png",
    gameVideoLauncherUrl: "avzxX43SVME?si=73ASA63NIph8HWhE",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Undecember/hero_1440x800.jpg",
  },
  {
    _id: "651574afb676067d292e4502",
    systemGameName: "Soul Dossier",
    commonGameName: "Soul Dossier",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/SOUL%20DOSSIER.jpg",
    gameClass: "STANDART",
    genre: "SURVIVAL",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=7f1k3NtH_UQ",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T12:42:23.916Z",
    updatedAt: "2024-07-03T10:48:22.307Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Soul_Dossier/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Soul_Dossier/logo.png",
    gameVideoLauncherUrl: "7f1k3NtH_UQ?si=nKSnMF-674RtshGW",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Soul_Dossier/hero_1440x800.jpg",
  },
  {
    _id: "65157537b676067d292e4510",
    systemGameName: "Stumble Guys",
    commonGameName: "Stumble Guys",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/STUMBLE%20GUYS.jpg",
    gameClass: "STANDART",
    genre: "FIGHTING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=DqzD79xYU1k",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T12:44:39.265Z",
    updatedAt: "2024-07-03T10:48:57.918Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Stumble_Guys/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Stumble_Guys/logo.png",
    gameVideoLauncherUrl: "abvbWS8XlFk?si=QK3gEGZAiMO1QFmS",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Stumble_Guys/hero_1440x800.jpg",
  },
  {
    _id: "65157606b676067d292e451d",
    systemGameName: "Shop Titans",
    commonGameName: "Shop Titans",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/SHOP%20TITANS.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=Z3li_cbJt5k",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T12:48:06.904Z",
    updatedAt: "2024-07-03T10:49:07.697Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Shop_Titans/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Shop_Titans/logo.png",
    gameVideoLauncherUrl: "Z3li_cbJt5k?si=5P1GxqU7XXfEbAlU",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Shop_Titans/hero_1440x800.jpg",
  },
  {
    _id: "651578fcb676067d292e454d",
    systemGameName: "Age of Empires III: Definitive Edition",
    commonGameName: "Age of Empires III: Definitive Edition",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage:
      "https://miraplay.cloud/images/AGE%20OF%20EMPIRES%20III%20DEFINITIVE%20EDITION.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=UJ6T4BquQH0",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:00:44.013Z",
    updatedAt: "2024-07-03T10:50:04.134Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Age_of_Empires_III_Definitive_Edition/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Age_of_Empires_III_Definitive_Edition/logo.png",
    gameVideoLauncherUrl: "UJ6T4BquQH0?si=ADZkuCyN3OiUY_sy",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Age_of_Empires_III_Definitive_Edition/hero_1440x800.jpg",
  },
  {
    _id: "65157a09b676067d292e4563",
    systemGameName: "Crossout",
    commonGameName: "Crossout",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/CROSSOUT.jpg",
    gameClass: "STANDART",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=gxXyhXZSJVo",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:05:13.079Z",
    updatedAt: "2024-07-03T10:51:08.918Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Crossout/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Crossout/logo.png",
    gameVideoLauncherUrl: "gxXyhXZSJVo?si=f7sIMI0-JV58Xx7N",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Crossout/hero_1440x800.jpg",
  },
  {
    _id: "65157a82b676067d292e456d",
    systemGameName: "Paladins",
    commonGameName: "Paladins®",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/PALADINS%C2%AE.jpeg",
    gameClass: "STANDART",
    genre: "MOBA",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=g4WHiMVq1-8",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:07:14.344Z",
    updatedAt: "2024-07-03T10:51:20.461Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Paladins/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Paladins/logo.png",
    gameVideoLauncherUrl: "fx5F1anRlJI?si=k_vbw7DQqoxaoSCH",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Paladins/hero_1440x800.jpg",
  },
  {
    _id: "65157b24b676067d292e4579",
    systemGameName: "Neverwinter",
    commonGameName: "Neverwinter",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/NEVERWINTER.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=bli0LR6kawI",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:09:56.342Z",
    updatedAt: "2024-07-03T10:52:10.535Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Neverwinter/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Neverwinter/logo.png",
    gameVideoLauncherUrl: "bli0LR6kawI?si=Pb-XEBtpfHsiXbYX",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Neverwinter/hero_1440x800.jpg",
  },
  {
    _id: "65157c56b676067d292e45a3",
    systemGameName: "Lords Mobile",
    commonGameName: "Lords Mobile",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/LORDS%20MOBILE.jpg",
    gameClass: "STANDART",
    genre: "MOBA",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=tD50K-NvNSM",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:15:02.739Z",
    updatedAt: "2024-07-03T10:52:19.631Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Lords_Mobile/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Lords_Mobile/logo.png",
    gameVideoLauncherUrl: "tD50K-NvNSM?si=DFFQVEx502GzilGN",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Lords_Mobile/hero_1440x800.jpg",
  },
  {
    _id: "65157cf3b676067d292e45b4",
    systemGameName: "My Singing Monsters",
    commonGameName: "My Singing Monsters",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/MY%20SINGING%20MONSTERS.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=KqreWm5ZpHw",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:17:39.786Z",
    updatedAt: "2024-07-03T10:52:31.591Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/MY_SINGING_MONSTERS/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/MY_SINGING_MONSTERS/logo.png",
    gameVideoLauncherUrl: "KqreWm5ZpHw?si=jCFkYLyygYICUkLf",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/MY_SINGING_MONSTERS/hero_1440x800.jpg",
  },
  {
    _id: "65157d97b676067d292e45cb",
    systemGameName: "Goose Goose Duck",
    commonGameName: "Goose Goose Duck",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/GOOSE%20GOOSE%20DUCK.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=bHrHDenJlG8",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:20:23.048Z",
    updatedAt: "2024-07-03T10:52:42.907Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/GOOSE_GOOSE_DUCK/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/GOOSE_GOOSE_DUCK/logo.png",
    gameVideoLauncherUrl: "bHrHDenJlG8?si=2AJ8CMvoNdvg5vMh",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/GOOSE_GOOSE_DUCK/hero_1440x800.jpg",
  },
  {
    _id: "65157e0bb676067d292e45e5",
    systemGameName: "RISK Global Domination",
    commonGameName: "RISK: Global Domination",
    gameDescription:
      "Бийтеся з противниками в стратегічній війні в офіційній цифровій версії класичної настільної гри Hasbro, яку люблять мільйони. Боріться проти держав Осі під час Першої світової війни, переживайте військові ігри проти зомбі-нежиті та бийтеся на фантастичних, футуристичних і науково-фантастичних картах.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/RISK%20GLOBAL%20DOMINATION.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=cPui_cv5XYs",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:22:19.943Z",
    updatedAt: "2024-07-03T10:52:56.400Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/RISK_GLOBAL_DOMINATION/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/RISK_GLOBAL_DOMINATION/logo.png",
    gameVideoLauncherUrl: "zRAOukLqYXw?si=29tIxCtPbWI-mHzr",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/RISK_GLOBAL_DOMINATION/hero_1440x800.jpg",
  },
  {
    _id: "65157e9bb676067d292e4618",
    systemGameName: "Rogue Company",
    commonGameName: "Rogue Company",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/ROGUE%20COMPANY.jpg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=cwLbCWDntVc",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:24:43.012Z",
    updatedAt: "2024-07-03T10:53:06.509Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Rouge_Company/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Rouge_Company/logo.png",
    gameVideoLauncherUrl: "cwLbCWDntVc?si=C4Wg4aSJcmvQ74te",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Rouge_Company/hero_1440x800.jpg",
  },
  {
    _id: "65157f9fb676067d292e466d",
    systemGameName: "Naval Action",
    commonGameName: "Naval Action",
    gameDescription:
      "Відеогра створена на рушії Unity3D, що забезпечує реалістичні моделі кораблів та відкритий світ карибських морських просторів, де за багаті землі борються такі держави як Велика Британія, Франція, Іспанія, Данія, США, Голландія, Швеція і пірати. Гра знаходиться в альфа версії, але стрімко розвивається.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/NAVAL%20ACTION.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=r2q0K9VbD2g",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:29:03.983Z",
    updatedAt: "2024-07-03T10:53:20.914Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Naval_Action/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Naval_Action/logo.png",
    gameVideoLauncherUrl: "r2q0K9VbD2g?si=CTZfZvkikTKbA4c0",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Naval_Action/hero_1440x800.jpg",
  },
  {
    _id: "651580f0b5b991eee7785235",
    systemGameName: "Fallout Shelter",
    commonGameName: "Fallout Shelter",
    gameDescription:
      "Гравці розбудовують підземне Сховище та керують ним як наглядачі. Гравці повинні стежити за устаткуванням і самими жителями сховища та постійно підтримувати їхній настрій у нормі. Максимум жителів — 200 осіб. Щоб Сховище нормально функціонувало і розвивалося, слід добувати ресурси, призначати людей на роботу у ​​​​відповідні приміщення, посилати їх в експедиції на поверхню. Це вимагає правильного розподілу їхніх умінь між параметрами сили, сприйняття, витривалості, харизми, інтелекту, спритності та вдачі, що відповідає системі S.P.E.C.I.A.L. основної серії ігор серії Fallout. Характеристики кожного персонажа впливають на те, наскільки він придатний для певного виду роботи. Поставлений на не відповідну для нього посаду, або хворий чи поранений, житель Сховища втрачатиме настрій, тим самими зменшуючи власну продуктивність. З часом населення зростає, але може настати перенаселення, за якого виробництво ресурсів падатиме.",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/FALLOUT%20SHELTER.jpg",
    gameClass: "STANDART",
    genre: "SURVIVAL",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=HY4jCjufLG8",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-28T13:34:40.761Z",
    updatedAt: "2024-07-03T10:53:30.998Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Fallout_Shelter/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Fallout_Shelter/logo.png",
    gameVideoLauncherUrl: "HY4jCjufLG8?si=jSTlU2Ie6pv2QdM0",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Fallout_Shelter/hero_1440x800.jpg",
  },
  {
    _id: "6516c2f4a8439571e469a34b",
    systemGameName: "EA",
    commonGameName: "EA",
    gameDescription:
      "Марка заснована в 1993 році і є однією з найуспішніших і найвідоміших марок серед спортивних ігор. Марка EA SPORTS — це автентичні спортивні симулятори та офіційні ліцензійні продукти по найпопулярніших видів спорту. Студія EA SPORTS у Ванкувері, Канада, використовує сучасні технології, як, наприклад, захоплення руху, що роблять руху спортсменів у грі максимально реалістичними. Крім того, студія співпрацює з багатьма відомими спортсменами з усього світу.",
    gameLaunchers: ["EA"],
    gameImage: "https://miraplay.cloud/images/ea.png",
    gameClass: "STANDART",
    genre: "LAUNCHERS",
    inTop: true,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=nDvbMlK-CNk",
    gameImages: [""],
    exactingness: "",
    createdAt: "2023-09-29T12:28:36.484Z",
    updatedAt: "2024-07-03T10:53:42.442Z",
    __v: 0,
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/EA_App/boxart_600x900.jpg",
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/EA_App/logo.png",
    gameVideoLauncherUrl: "yo9VFhYCbVM?si=UthZgmgXLWFID4tH",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/EA_App/hero_1440x800.jpg",
  },
  {
    _id: "67053d9c9e209881b3f2aedf",
    systemGameName: "RAGE_Multiplayer",
    commonGameName: "RAGE Multiplayer",
    gameDescription: "Гра доступна лише після оплати мінімального тарифу",
    gameLaunchers: ["RAGE Multiplayer"],
    gameImage: "https://miraplay.cloud/images/RAGE_MP.png",
    gameClass: "VIP",
    genre: "ONLINE",
    inTop: true,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: ["https://miraplay.cloud/images/RAGE_MP.png"],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/RageMP/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/RageMP/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/RageMP/boxart_600x900.jpg",
    exactingness: "",
    createdAt: "2024-10-08T14:11:40.691Z",
    updatedAt: "2024-11-20T18:20:27.066Z",
    __v: 0,
  },
  {
    _id: "6784dfa3b21c2462ece43009",
    systemGameName: "hogwards",
    commonGameName: "Hogwarts Legacy",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/HOGWARDS.jpg",
    gameClass: "VIP",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/hogwards/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/hogwards/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/hogwards/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-13T09:40:51.044Z",
    updatedAt: "2025-02-05T08:47:00.496Z",
    __v: 0,
  },
  {
    _id: "6784e094b21c2462ece4315e",
    systemGameName: "stalker_2",
    commonGameName: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/STALKER2.jpg",
    gameClass: "VIP",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/stalker_2/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/stalker_2/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/stalker_2/boxart_600x900.png",
    exactingness: "75",
    createdAt: "2025-01-13T09:44:52.754Z",
    updatedAt: "2025-02-05T10:20:11.409Z",
    __v: 0,
  },
  {
    _id: "679c9b60915a817612a695c1",
    systemGameName: "Lost_Light",
    commonGameName: "Lost Light",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Lost_Light.jpg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=-DLErO38UmE",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Lost_Light/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Lost_Light/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Lost_Light/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:44:00.338Z",
    updatedAt: "2025-02-05T09:22:18.107Z",
    __v: 0,
  },
  {
    _id: "679c9baf915a817612a69630",
    systemGameName: "Path_of_Exile_2",
    commonGameName: "Path of Exile 2",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Path_of_Exile_2.png",
    gameClass: "VIP",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=JCDIBA2Icls",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Path_of_Exile_2/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Path_of_Exile_2/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Path_of_Exile_2/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:45:19.724Z",
    updatedAt: "2025-02-05T09:56:31.997Z",
    __v: 0,
  },
  {
    _id: "679c9c88915a817612a69763",
    systemGameName: "Warframe",
    commonGameName: "Warframe",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Warframe.png",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Warframe/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Warframe/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Warframe/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:48:56.569Z",
    updatedAt: "2025-02-05T12:40:48.734Z",
    __v: 0,
  },
  {
    _id: "679c9ccd915a817612a697cc",
    systemGameName: "Marvel_Rivals",
    commonGameName: "Marvel Rivals",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Marvel_Rivals.webp",
    gameClass: "STANDART",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Marvel_Rivals/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Marvel_Rivals/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Marvel_Rivals/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:50:05.166Z",
    updatedAt: "2025-02-05T09:25:04.865Z",
    __v: 0,
  },
  {
    _id: "679c9cee915a817612a697f8",
    systemGameName: "Diablo_IV",
    commonGameName: "Diablo® IV",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Diablo®IV.webp",
    gameClass: "VIP",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=Ro26B394ZBM",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Diablo_IV/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Diablo_IV/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Diablo_IV/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:50:38.968Z",
    updatedAt: "2025-02-05T08:34:59.260Z",
    __v: 0,
  },
  {
    _id: "679c9d0c915a817612a69823",
    systemGameName: "Titanfall_2",
    commonGameName: "Titanfall® 2",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Titanfall®2.jpg",
    gameClass: "VIP",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=VqeMjHmL9eg&t=1s",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Titanfall_2/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Titanfall_2/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Titanfall_2/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:51:08.676Z",
    updatedAt: "2025-02-05T12:27:46.810Z",
    __v: 0,
  },
  {
    _id: "679c9d93915a817612a698e3",
    systemGameName: "Car_Dealer_Simulator_Prologue_Early_Days",
    commonGameName: "Car Dealer Simulator Prologue - Early Days",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Car_Dealer_Simulator.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Car_Dealer_Simulator_Prologue_Early_Days/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Car_Dealer_Simulator_Prologue_Early_Days/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Car_Dealer_Simulator_Prologue_Early_Days/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:53:23.837Z",
    updatedAt: "2025-02-05T08:18:51.640Z",
    __v: 0,
  },
  {
    _id: "679c9dd2915a817612a69927",
    systemGameName: "King_Arthur_Legends_Rise",
    commonGameName: "King Arthur Legends Rise",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/King_Arthur_Legends_Rise.avif",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/King_Arthur_Legends_Rise/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/King_Arthur_Legends_Rise/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/King_Arthur_Legends_Rise/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:54:26.360Z",
    updatedAt: "2025-02-05T09:19:28.945Z",
    __v: 0,
  },
  {
    _id: "679c9e54915a817612a699b5",
    systemGameName: "Once_Human",
    commonGameName: "Once Human",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Once_Human.avif",
    gameClass: "STANDART",
    genre: "SURVIVAL",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=XTwOAAGhLCk",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Once_Human/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Once_Human/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Once_Human/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:56:36.119Z",
    updatedAt: "2025-02-05T12:43:38.675Z",
    __v: 0,
  },
  {
    _id: "679c9eb3915a817612a69a1d",
    systemGameName: "STAR_WARS_The_Old_Republic",
    commonGameName: "STAR WARS™ The Old Republic™",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/STARWARS_The_Old_Republic.webp",
    gameClass: "STANDART",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/STAR_WARS_The_Old_Republic/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/STAR_WARS_The_Old_Republic/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/STAR_WARS_The_Old_Republic/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:58:11.510Z",
    updatedAt: "2025-02-05T10:53:52.732Z",
    __v: 0,
  },
  {
    _id: "679c9ef1915a817612a69a5f",
    systemGameName: "Asphalt_Legends_Unite",
    commonGameName: "Asphalt Legends Unite",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Asphalt_Legends_Unite.avif",
    gameClass: "STANDART",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=rH-eZd01NEQ",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Asphalt_Legends_Unite/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Asphalt_Legends_Unite/hero_1440x800.png",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Asphalt_Legends_Unite/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T09:59:13.178Z",
    updatedAt: "2025-02-04T16:08:19.303Z",
    __v: 0,
  },
  {
    _id: "679c9f3f915a817612a69ab5",
    systemGameName: "Strinova",
    commonGameName: "Strinova",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Strinova1.jpg",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=Txab4Vr7o8k",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Strinova/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Strinova/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Strinova/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:00:31.385Z",
    updatedAt: "2025-02-05T10:56:29.016Z",
    __v: 0,
  },
  {
    _id: "679c9f70915a817612a69b08",
    systemGameName: "World_of_Tanks_Blitz",
    commonGameName: "World of Tanks Blitz",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/World_of_Tanks_Blitz.jpeg",
    gameClass: "STANDART",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=_Vtvjg8dYqI",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Tanks_Blitz/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Tanks_Blitz/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/World_of_Tanks_Blitz/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:01:20.481Z",
    updatedAt: "2025-02-05T13:22:59.985Z",
    __v: 0,
  },
  {
    _id: "679ca04a915a817612a69c0d",
    systemGameName: "DCS_World_Steam_Edition",
    commonGameName: "DCS World Steam Edition",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/DCS_World_Steam.jpg",
    gameClass: "STANDART",
    genre: "FIGHTING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=4Q37cbS0XKY",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/DCS_World_Steam_Edition/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/DCS_World_Steam_Edition/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/DCS_World_Steam_Edition/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:04:58.779Z",
    updatedAt: "2025-02-05T08:17:02.402Z",
    __v: 0,
  },
  {
    _id: "679ca0b1915a817612a69c7b",
    systemGameName: "Assetto_Corsa_Competizione",
    commonGameName: "Assetto Corsa Competizione",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Assetto_Corsa_Competizione1.jpg",
    gameClass: "VIP",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=CYncAnd31Q8",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Assetto_Corsa_Competizione/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Assetto_Corsa_Competizione/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Assetto_Corsa_Competizione/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:06:41.206Z",
    updatedAt: "2025-02-04T16:15:05.341Z",
    __v: 0,
  },
  {
    _id: "679ca0d6915a817612a69cb4",
    systemGameName: "Assetto_Corsa_EVO",
    commonGameName: "Assetto Corsa EVO",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Assetto_Corsa_EVO.webp",
    gameClass: "VIP",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=0uOkigs9hnY",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Assetto_Corsa_EVO/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Assetto_Corsa_EVO/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Assetto_Corsa_EVO/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:07:18.692Z",
    updatedAt: "2025-02-04T16:20:02.191Z",
    __v: 0,
  },
  {
    _id: "679ca0f8915a817612a69cd8",
    systemGameName: "Need_for_Speed_Unbound",
    commonGameName: "Need for Speed™ Unbound",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Need_for_Speed™_Unbound.jpg",
    gameClass: "VIP",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=H2Y8XCe7F9E",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Need_for_Speed_Unbound/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Need_for_Speed_Unbound/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Need_for_Speed_Unbound/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:07:52.411Z",
    updatedAt: "2025-02-05T09:48:49.157Z",
    __v: 0,
  },
  {
    _id: "679ca122915a817612a69d0c",
    systemGameName: "Need_for_Speed_Heat",
    commonGameName: "Need for Speed™ Heat",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Need_for_Speed™_Heat.jpg",
    gameClass: "VIP",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=9ewiJJe_nYI",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Need_for_Speed_Heat/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Need_for_Speed_Heat/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Need_for_Speed_Heat/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:08:34.318Z",
    updatedAt: "2025-02-05T09:30:10.734Z",
    __v: 0,
  },
  {
    _id: "679ca154915a817612a69d4d",
    systemGameName: "Delta_Force",
    commonGameName: "Delta Force",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Delta_Force.webp",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=_hwtosVfqog",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Delta_Force/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Delta_Force/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Delta_Force/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:09:24.583Z",
    updatedAt: "2025-02-05T08:24:31.949Z",
    __v: 0,
  },
  {
    _id: "679ca17f915a817612a69d80",
    systemGameName: "The_First_Descendant",
    commonGameName: "The First Descendant",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/The_First_Descendant1.jpg",
    gameClass: "STANDART",
    genre: "SURVIVAL",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=UdmgmufAd9Q",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/The_First_Descendant/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/The_First_Descendant/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/The_First_Descendant/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:10:07.217Z",
    updatedAt: "2025-02-05T12:22:34.960Z",
    __v: 0,
  },
  {
    _id: "679ca1c7915a817612a69dc3",
    systemGameName: "Torchlight_Infinite",
    commonGameName: "Torchlight Infinite",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Torchlight_Infinite.avif",
    gameClass: "STANDART",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Torchlight_Infinite/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Torchlight_Infinite/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Torchlight_Infinite/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:11:19.737Z",
    updatedAt: "2025-02-05T12:38:08.145Z",
    __v: 0,
  },
  {
    _id: "679ca1e5915a817612a69dda",
    systemGameName: "Star_Trek_Online",
    commonGameName: "Star Trek Online",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Star_Trek_Online.png",
    gameClass: "STANDART",
    genre: "ONLINE",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Star_Trek_Online/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Star_Trek_Online/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Star_Trek_Online/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:11:49.229Z",
    updatedAt: "2025-02-05T10:47:43.723Z",
    __v: 0,
  },
  {
    _id: "679ca21c915a817612a69e15",
    systemGameName: "Idle_Champions_of_the_Forgotten_Realms",
    commonGameName: "Idle Champions of the Forgotten Realms",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage:
      "https://miraplay.cloud/images/Idle_Champions of_the_ForgottenRealms1.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Idle_Champions_of_the_Forgotten_Realms/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Idle_Champions_of_the_Forgotten_Realms/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Idle_Champions_of_the_Forgotten_Realms/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:12:44.347Z",
    updatedAt: "2025-02-05T09:15:30.348Z",
    __v: 0,
  },
  {
    _id: "679ca243915a817612a69e44",
    systemGameName: "The_Lord_of_the_Rings_Online",
    commonGameName: "The Lord of the Rings Online™",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/The_Lord_of_the_Rings_Online.jpg",
    gameClass: "STANDART",
    genre: "MMORPG",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/The_Lord_of_the_Rings_Online/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/The_Lord_of_the_Rings_Online/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/The_Lord_of_the_Rings_Online/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:13:23.375Z",
    updatedAt: "2025-02-05T12:25:17.802Z",
    __v: 0,
  },
  {
    _id: "679ca256915a817612a69e55",
    systemGameName: "EMERGENCY",
    commonGameName: "EMERGENCY",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/EMERGENCY.jpg_large",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/EMERGENCY/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/EMERGENCY/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/EMERGENCY/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:13:42.277Z",
    updatedAt: "2025-02-05T08:38:49.537Z",
    __v: 0,
  },
  {
    _id: "679ca27a915a817612a69e88",
    systemGameName: "Predecessor",
    commonGameName: "Predecessor",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Predecessor.png",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Predecessor/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Predecessor/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Predecessor/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:14:18.894Z",
    updatedAt: "2025-02-05T09:59:42.370Z",
    __v: 0,
  },
  {
    _id: "679ca290915a817612a69e97",
    systemGameName: "Quake_Champions",
    commonGameName: "Quake Champions",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Quake_Champions.png",
    gameClass: "STANDART",
    genre: "SHOOTERS",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Quake_Champions/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Quake_Champions/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Quake_Champions/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:14:40.254Z",
    updatedAt: "2025-02-05T10:03:36.445Z",
    __v: 0,
  },
  {
    _id: "679ca2c8915a817612a69ed0",
    systemGameName: "Game_of_Thrones_Winter_is_Coming",
    commonGameName: "Game of Thrones Winter is Coming",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Game_of_Thrones_Winter.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Game_of_Thrones_Winter_is_Coming/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Game_of_Thrones_Winter_is_Coming/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Game_of_Thrones_Winter_is_Coming/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:15:36.704Z",
    updatedAt: "2025-02-05T08:43:02.500Z",
    __v: 0,
  },
  {
    _id: "679ca2ec915a817612a69eff",
    systemGameName: "WGT_Golf",
    commonGameName: "WGT Golf",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/WGT%20Golf.jpg",
    gameClass: "STANDART",
    genre: "STRATEGY",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/WGT_Golf/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/WGT_Golf/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/WGT_Golf/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:16:12.273Z",
    updatedAt: "2025-02-05T12:57:05.123Z",
    __v: 0,
  },
  {
    _id: "679ca308915a817612a69f16",
    systemGameName: "BeamNG_drive",
    commonGameName: "BeamNG.drive",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/BeamNG.drive.png",
    gameClass: "VIP",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/BeamNG_drive/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/BeamNG_drive/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/BeamNG_drive/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:16:40.979Z",
    updatedAt: "2025-02-04T16:25:20.703Z",
    __v: 0,
  },
  {
    _id: "679ca358915a817612a69f66",
    systemGameName: "Tokyo_Xtreme_Racer",
    commonGameName: "Tokyo Xtreme Racer",
    gameDescription: "",
    gameLaunchers: ["Steam"],
    gameImage: "https://miraplay.cloud/images/Tokyo_Xtreme_Racer1.jpg",
    gameClass: "VIP",
    genre: "RACING",
    inTop: false,
    releaseDate: "",
    publisher: "",
    gameVideoUrl: "https://www.youtube.com/watch?v=umlztIQ7HeE",
    gameVideoLauncherUrl: "",
    gameImages: [""],
    gameLogo:
      "https://miraplay.cloud/images/Game_Library_assest/Tokyo_Xtreme_Racer/logo.png",
    gameHero:
      "https://miraplay.cloud/images/Game_Library_assest/Tokyo_Xtreme_Racer/hero_1440x800.jpg",
    gameBoxArt:
      "https://miraplay.cloud/images/Game_Library_assest/Tokyo_Xtreme_Racer/boxart_600x900.png",
    exactingness: "",
    createdAt: "2025-01-31T10:18:00.653Z",
    updatedAt: "2025-02-05T12:33:10.264Z",
    __v: 0,
  },
];
